version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: muplonen
      POSTGRES_USER: muplonen
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080